services:
  next:
    container_name: next
    build:
      context: .
      target: dev
      dockerfile: ./docker/next/Dockerfile
    volumes:
      - type: bind
        source: ./next
        target: /src
      - type: volume
        source: node_modules_v2
        target: /src/node_modules
    ports:
      - 3000:3000
      - 6006:6006
      - 3100:3100
    tty: true
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
      - CARD_ENDPOINT=http://localhost:3100/cards

volumes:
  node_modules_v2:


